name: deploy_frontend
  #Deploys whens push is made to frontend folder

on:
    push:
        branches: [ main ]
        paths: 
          - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/actions/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name stazureresume -d '$web' -s frontend/ --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cdn-azure-resume" --name "sanjivazureresume" --resource-group "rg-azure-resume"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
